package com.tw.commandend;

import com.tw.commandend.command.Command;
import com.tw.commandend.command.MainMenuCommand;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class GradeCommandApp {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String args[]) {
        Command command = new MainMenuCommand("0");
        command.input();
    }
}
