import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class GradeCommandApp {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String args[]){

    }
}
