import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String args[]){

        try {
            String content = new String(Files.readAllBytes(Paths.get("data/words.txt")));
            System.out.println(content);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
